"""C code export pipeline for claudeverb algorithms.

Generates .h and .c files, RAM estimates, and Hothouse AudioCallback
templates from any algorithm with to_c_struct() and to_c_process_fn().

Uses Python f-strings (not Jinja2) per project decision.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone


def _snake_case(name: str) -> str:
    """Convert CamelCase class name to snake_case for C function names.

    Examples:
        Freeverb -> freeverb
        DattorroPlate -> dattorro_plate
        FDNReverb -> fdn_reverb
    """
    # Insert underscore before uppercase letters that follow lowercase
    s1 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    # Insert underscore between consecutive uppercase and following lowercase
    s2 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s1)
    return s2.lower()


def _state_name(algo) -> str:
    """Get the C state struct name from to_c_struct() output."""
    struct_text = algo.to_c_struct()
    match = re.search(r"}\s*(\w+State)\s*;", struct_text)
    if match:
        return match.group(1)
    # Fallback: derive from class name
    cls_name = type(algo).__name__
    return f"{cls_name}State"


def generate_header(algo, params: dict, knob_mapping: dict | None = None) -> str:
    """Generate a .h header file for the given algorithm.

    Args:
        algo: Algorithm instance with to_c_struct(), param_specs.
        params: Current parameter values dict.
        knob_mapping: Optional dict mapping param names to Hothouse knob names.

    Returns:
        Complete .h file content as string.
    """
    cls_name = type(algo).__name__
    snake = _snake_case(cls_name)
    state_name = _state_name(algo)
    guard = f"{snake.upper()}_H"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Build parameter comment block
    param_lines = []
    for pname, pval in params.items():
        spec = algo.param_specs.get(pname, {})
        label = spec.get("label", pname)
        pmin = spec.get("min", "?")
        pmax = spec.get("max", "?")
        param_lines.append(f" *   {label}: {pval} (range: {pmin}-{pmax})")

    param_block = "\n".join(param_lines) if param_lines else " *   (no parameters)"

    struct_body = algo.to_c_struct()

    return f"""\
#ifndef {guard}
#define {guard}

/*
 * {cls_name} reverb algorithm
 * Generated by claudeverb C export
 * Timestamp: {timestamp}
 *
 * Current parameter settings:
{param_block}
 */

#include <math.h>

{struct_body}
void {snake}_init({state_name}* state);
void {snake}_process({state_name}* state, const float* input,
                     float* output_left, float* output_right,
                     int num_samples);

#endif /* {guard} */
"""


def generate_source(algo, params: dict) -> str:
    """Generate a .c source file for the given algorithm.

    Args:
        algo: Algorithm instance with to_c_struct(), to_c_process_fn(), param_specs.
        params: Current parameter values dict.

    Returns:
        Complete .c file content as string.
    """
    cls_name = type(algo).__name__
    snake = _snake_case(cls_name)
    state_name = _state_name(algo)

    # Build init function that sets defaults from current params
    init_lines = []
    init_lines.append(f"void {snake}_init({state_name}* state) {{")
    init_lines.append("    // Zero entire struct")
    init_lines.append(f"    memset(state, 0, sizeof({state_name}));")
    init_lines.append("")
    init_lines.append("    // Set parameter defaults from current values")

    specs = algo.param_specs
    for pname, pval in params.items():
        spec = specs.get(pname, {})
        label = spec.get("label", pname)
        ptype = spec.get("type", "knob")

        # Skip switch-type params -- handle separately
        if ptype == "switch":
            init_lines.append(f"    // {label}: {pval}")
            continue

        # C struct field name matches param name
        if isinstance(pval, float):
            init_lines.append(
                f"    state->{pname} = {pval:.4f}f;  /* {label} */"
            )
        else:
            init_lines.append(
                f"    state->{pname} = {pval};  /* {label} */"
            )

    init_lines.append("")
    init_lines.append("    state->sample_rate = 48000;")
    init_lines.append("}")
    init_body = "\n".join(init_lines)

    process_body = algo.to_c_process_fn()

    return f"""\
#include "{cls_name}.h"
#include <string.h>
#include <math.h>

{init_body}

{process_body}
"""


def estimate_ram(algo) -> dict:
    """Estimate RAM usage from the algorithm's C struct definition.

    Parses to_c_struct() output to find array declarations and scalars.

    Returns:
        Dict with keys: delay_lines_kb, filters_kb, matrices_kb, total_kb,
        fits_sram, fits_sdram, sdram_candidates, breakdown.
    """
    struct_text = algo.to_c_struct()

    # Find all array declarations: type name[size]
    float_arrays = re.findall(
        r"float\s+(\w+)\[(\d+)\]", struct_text
    )
    int_arrays = re.findall(
        r"int\s+(\w+)\[(\d+)\]", struct_text
    )

    # Count scalars (float/int without brackets)
    float_scalars = len(re.findall(
        r"float\s+\w+\s*;", struct_text
    ))
    int_scalars = len(re.findall(
        r"int\s+\w+\s*;", struct_text
    ))

    # Categorize arrays
    delay_bytes = 0
    filter_bytes = 0
    matrix_bytes = 0
    sdram_candidates = []
    breakdown = {}

    for name, size_str in float_arrays:
        size = int(size_str)
        nbytes = size * 4  # float = 4 bytes
        breakdown[name] = nbytes

        # Categorize by name
        if any(k in name for k in ("delay", "buf", "pre_delay")):
            delay_bytes += nbytes
        elif any(k in name for k in ("damp", "dc", "bw", "filter", "lpf")):
            filter_bytes += nbytes
        elif any(k in name for k in ("matrix", "hadamard")):
            matrix_bytes += nbytes
        else:
            delay_bytes += nbytes  # default to delay category

        # SDRAM candidates: buffers > 4096 floats (16 KB)
        if size > 4096:
            sdram_candidates.append(name)

    for name, size_str in int_arrays:
        size = int(size_str)
        nbytes = size * 4  # int = 4 bytes
        breakdown[name] = nbytes
        delay_bytes += nbytes

    scalar_bytes = (float_scalars + int_scalars) * 4

    total_bytes = delay_bytes + filter_bytes + matrix_bytes + scalar_bytes
    # Add 10% padding for struct alignment
    total_bytes_padded = int(total_bytes * 1.1)

    return {
        "delay_lines_kb": round(delay_bytes / 1024, 2),
        "filters_kb": round(filter_bytes / 1024, 2),
        "matrices_kb": round(matrix_bytes / 1024, 2),
        "total_kb": round(total_bytes_padded / 1024, 2),
        "fits_sram": total_bytes_padded < 512 * 1024,
        "fits_sdram": total_bytes_padded < 64 * 1024 * 1024,
        "sdram_candidates": sdram_candidates,
        "breakdown": breakdown,
    }


def generate_audio_callback(algo, knob_mapping: dict) -> str:
    """Generate Hothouse AudioCallback template for the algorithm.

    Args:
        algo: Algorithm instance with param_specs.
        knob_mapping: Dict mapping param names to Hothouse knob identifiers
                      (e.g., {"room_size": "KNOB_1", "damping": "KNOB_2"}).

    Returns:
        Complete AudioCallback .cpp file content as string.
    """
    cls_name = type(algo).__name__
    snake = _snake_case(cls_name)
    state_name = _state_name(algo)
    specs = algo.param_specs

    # Build knob parameter init lines for main()
    knob_init_lines = []
    knob_read_lines = []

    for param_name, knob_id in knob_mapping.items():
        spec = specs.get(param_name, {})
        pmin = spec.get("min", 0)
        pmax = spec.get("max", 100)
        label = spec.get("label", param_name)
        # Extract knob index (KNOB_1 -> 0, KNOB_2 -> 1, etc.)
        knob_idx_match = re.search(r"(\d+)", knob_id)
        if knob_idx_match:
            knob_idx = int(knob_idx_match.group(1)) - 1
        else:
            knob_idx = 0

        knob_init_lines.append(
            f"    knobs[{knob_idx}].Init(hw.GetKnobValue("
            f"Hothouse::{knob_id}), {float(pmin):.1f}f, {float(pmax):.1f}f, "
            f"Parameter::LINEAR);  // {label}"
        )
        knob_read_lines.append(
            f"        state.{param_name} = knobs[{knob_idx}].Process();  "
            f"// {label} ({knob_id})"
        )

    knob_init_block = "\n".join(knob_init_lines) if knob_init_lines else "    // No knobs mapped"
    knob_read_block = "\n".join(knob_read_lines) if knob_read_lines else "        // No knobs mapped"

    return f"""\
/*
 * {cls_name} AudioCallback for Cleveland Music Co. Hothouse
 * Generated by claudeverb C export
 *
 * Build: arm-none-eabi-gcc with libDaisy and DaisySP
 * Flash: make program-dfu
 */

#include "daisysp.h"
#include "hothouse.h"
#include "{cls_name}.h"

using clevelandmusicco::Hothouse;
using daisy::AudioHandle;
using daisy::Parameter;

Hothouse hw;
{state_name} state;
Parameter knobs[6];
bool bypass = true;

void AudioCallback(AudioHandle::InputBuffer in,
                   AudioHandle::OutputBuffer out,
                   size_t size) {{
    hw.ProcessAllControls();

    // Read knob values
    if (!bypass) {{
{knob_read_block}
    }}

    // Bypass / footswitch toggle
    if (hw.switches[Hothouse::FOOTSWITCH_1].RisingEdge()) {{
        bypass = !bypass;
    }}
    hw.SetLed(Hothouse::LED_1, !bypass);

    if (bypass) {{
        for (size_t i = 0; i < size; i++) {{
            out[0][i] = in[0][i];
            out[1][i] = in[1][i];
        }}
        return;
    }}

    // Process reverb
    {snake}_process(&state, in[0], out[0], out[1], size);
}}

int main(void) {{
    hw.Init();
    hw.SetAudioBlockSize(48);
    hw.SetAudioSampleRate(daisy::SaiHandle::Config::SampleRate::SAI_48KHZ);

    // Initialize reverb state
    {snake}_init(&state);

    // Initialize knob parameters
{knob_init_block}

    hw.StartAudio(AudioCallback);

    while (1) {{}}
}}
"""


def export_to_files(
    algo,
    params: dict,
    knob_mapping: dict,
    output_dir: str = "daisyexport",
) -> dict:
    """Export algorithm to .h and .c files.

    Args:
        algo: Algorithm instance.
        params: Current parameter values.
        knob_mapping: Knob-to-parameter mapping.
        output_dir: Directory to write files to.

    Returns:
        Dict with header_path, source_path, callback_path, ram_estimate keys.
    """
    cls_name = type(algo).__name__
    os.makedirs(output_dir, exist_ok=True)

    header_path = os.path.join(output_dir, f"{cls_name}.h")
    source_path = os.path.join(output_dir, f"{cls_name}.c")
    callback_path = os.path.join(output_dir, f"{cls_name}_callback.cpp")

    header_content = generate_header(algo, params, knob_mapping)
    source_content = generate_source(algo, params)
    callback_content = generate_audio_callback(algo, knob_mapping)
    ram_est = estimate_ram(algo)

    with open(header_path, "w") as f:
        f.write(header_content)
    with open(source_path, "w") as f:
        f.write(source_content)
    with open(callback_path, "w") as f:
        f.write(callback_content)

    return {
        "header_path": header_path,
        "source_path": source_path,
        "callback_path": callback_path,
        "ram_estimate": ram_est,
    }
